services:
  postgres:
    container_name: blog_postgres_db
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=blogDb'
      - 'POSTGRES_PASSWORD=secret_password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
