CREATE SEQUENCE post_seq
  START WITH 1001
  INCREMENT BY 1
  MINVALUE 1001;

CREATE TABLE post (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       VARCHAR(30),
  title         VARCHAR(30),
  body          VARCHAR(255),
  date_added    DATE,
  is_blocked    BOOLEAN
);

CREATE INDEX post_userId_idx ON post (user_id);